// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiZy688Ex-a61oGpQUrheVt8JJyqzyDq4',
    appId: '1:872384761336:web:3261bd52fde5e2c5d69a0d',
    messagingSenderId: '872384761336',
    projectId: 'mottu-marvel-ba3fa',
    authDomain: 'mottu-marvel-ba3fa.firebaseapp.com',
    storageBucket: 'mottu-marvel-ba3fa.appspot.com',
    measurementId: 'G-8ZVQ3ZKSQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACr9EQhXeQcpTZNXTkvfIp3Hmf2e9iCyM',
    appId: '1:872384761336:android:728a4427b8cce937d69a0d',
    messagingSenderId: '872384761336',
    projectId: 'mottu-marvel-ba3fa',
    storageBucket: 'mottu-marvel-ba3fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1zBl-7gQCe5kl25E-NvnpwdGBNuPxhB4',
    appId: '1:872384761336:ios:0d3b2b78ca719ff2d69a0d',
    messagingSenderId: '872384761336',
    projectId: 'mottu-marvel-ba3fa',
    storageBucket: 'mottu-marvel-ba3fa.appspot.com',
    iosBundleId: 'com.mottu.marvel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1zBl-7gQCe5kl25E-NvnpwdGBNuPxhB4',
    appId: '1:872384761336:ios:0d3b2b78ca719ff2d69a0d',
    messagingSenderId: '872384761336',
    projectId: 'mottu-marvel-ba3fa',
    storageBucket: 'mottu-marvel-ba3fa.appspot.com',
    iosBundleId: 'com.mottu.marvel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiZy688Ex-a61oGpQUrheVt8JJyqzyDq4',
    appId: '1:872384761336:web:fc3cbf3cf4f7c14ed69a0d',
    messagingSenderId: '872384761336',
    projectId: 'mottu-marvel-ba3fa',
    authDomain: 'mottu-marvel-ba3fa.firebaseapp.com',
    storageBucket: 'mottu-marvel-ba3fa.appspot.com',
    measurementId: 'G-Y95K1GE1SK',
  );
}
